services:
  - type: web
    name: stock-tracker-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: FB_PAGE_TOKEN
        sync: false
